version: "3"
services:
  django:
    image: python:3.9
    networks:
      - local
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: bash -c "cd /app/backend && pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"

  vue:
    image: node:16
    networks:
      - local
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: bash -c "cd /app/frontend/financialplanner && npm install && npm install -g @vue/cli && npm run serve"

networks:
  local: