# Generated by Django 4.0 on 2022-01-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='income',
            field=models.BooleanField(default=False),
        ),
    ]
